#FACEBOOK
FACEBOOK_APP_ID: '2379637342147222'
FACEBOOK_APP_SECRET: 02dcddde77759aac736b4c7f7e41ce09
FACEBOOK_CALLBACK_URL: http://localhost:3000/users/auth/facebook/callback
#TWITTER
TWITTER_APP_ID: qIInw2sialDrOTuxKyhnnS3vD
TWITTER_APP_SECRET: 83n5QyQqoDU3ccmlZwNAZHjZ9s637wMh2VQlG9KIA8Qfnvbz7L 
TWITTER_ACCESS_TOKEN: 1192405340232372224-8XT0IT9jgwSsOSLelrZF4K8U5Y0By1 
TWITTER_ACCESS_TOKEN_SECRET: f1fJlzsuveqExy9PW7CMksipUbUMF6H5PSQlUfJYNJIsy
TWITTER_CALLBACK_URL: http://127.0.0.1:3000/
#LINKEDIN
LINKEDIN_APP_ID: 813g5x5gtijpqk
LINKEDIN_APP_SECRET: dqyPl979gUV5dsyD
LINKEDIN_CALLBACK_URL: http://localhost:3000/users/auth/linkedin/callback
#INSTAGRAM
INSTAGRAM_ID: '564175654338523'
INSTAGRAM_SECRET: 'f9e6bd77cba1e5b2f63154cf87c33424'
INSTAGRAM_CALLBACK_URL: http://localhost:3000/users/auth/instagram/callback
#GOOGLE
GOOGLE_CLIENT_ID: 302401557727-7sq59qfkh59p9jehltftmuepfn8c968m.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: OPE_w7x7bwuFdMB6aCIsx1Z4
GOOGLE_CALLBACK_URL: http://localhost:3000/users/auth/google_oauth2/callback

